
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - invoke build.install-package
  - invoke test.lint
  - invoke integration.clean
  - invoke integration.version
  - invoke integration.initialize
  - invoke unit.pytest
  - invoke integration.analyze-policy
  - invoke integration.query
  - invoke integration.write-policy
  - invoke test.security
