site_name: Policy Sentry
theme: material
use_directory_urls: true
markdown_extensions:
    - codehilite
    - tables

nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Installation: 'installation.md'
  - Tutorial: 'tutorial.md'
  - Cheat Sheet: 'cheat-sheet.md'

  - "<b>Writing Policies</b>":
    - CRUD Mode: 'writing-policies/crud-mode.md'
    - "<i>Example</i>: Basic CRUD": 'writing-policies/access-levels-example.md'
    - "<b>Wildcard-only</b>":
      - Introduction: 'writing-policies/wildcard-only/introduction.md'
      - Single actions: 'writing-policies/wildcard-only/single-actions.md'
      - "<i>Example</i>: Single actions": 'writing-policies/wildcard-only/example-single-actions.md'
      - Service-wide: 'writing-policies/wildcard-only/service-wide.md'
      - "<i>Example</i>: Service-wide": 'writing-policies/wildcard-only/example-service-wide.md'
      - "<i>Example</i>: Combining approaches": 'writing-policies/wildcard-only/combined-approaches.md'
    - "Example: Skipping Resource Constraints": 'writing-policies/overrides.md'
    - Minimizing characters: 'writing-policies/minimization.md'
    - Actions Mode: 'writing-policies/actions-mode.md'

  - "<b>Querying the IAM Database</b>":
    - Action Table: 'querying/action-table.md'
    - ARN Table: 'querying/arn-table.md'
    - Condition Table: 'querying/condition-table.md'

  - "<b>Other Topics</b>":
    - Terraform: 'other/terraform.md'
    - Fetching the latest IAM Database: 'other/initialize.md'
    - Docker: 'other/docker.md'


  - "<b>Contributing</b>":
    - Contributing: 'contributing/contributing.md'
    - Documentation: 'contributing/documentation.md'
    - Testing: 'contributing/testing.md'
    - IAM database: 'contributing/iam-database.md'
    - Versioning: 'contributing/versioning.md'
    - Roadmap: 'contributing/roadmap.md'

  - "<b>Appendices</b>":
    - Comparison to other tools: 'appendices/comparison-to-related-tools.md'
    - Implementation Strategy: 'appendices/implementation-strategy.md'
    - Minimization: 'appendices/minimization.md'
    - IAM Policies: 'appendices/iam-policies.md'
